### PR TITLE
Expose ParseTimestamp for parsing the postgres timestamp format

### PR DESCRIPTION
**Pull request by danhhz**
Make it return errors where it used to panic, and add a couple tests for things that used to panic.

For https://github.com/cockroachdb/cockroach/issues/4872.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/pq/5)

### CODE REVIEW

**Comment by danhhz** [comment]
Btw, I ran https://github.com/dvyukov/go-fuzz on this to help check if I caught all the panics. I could commit the fuzz function and the working dir if we think that's interesting (though I'm not sure it's really all that interesting for this).

**Comment by danhhz** [comment]
@tamird do you want to take a look at this?

**Comment by tamird** [comment]
Yeah will do but probably tomorrow. I'd leave the fuzzing out; I doubt
upstream will want it.

**Comment by bdarnell** [comment]
I'm not sure it's worth it for this, but it might be nice to check the fuzzing stuff in somewhere even if it's not in this repo. @tschottdorf has a (now very old) branch with a fuzzing setup for our sql parser: https://github.com/tschottdorf/cockroach/commits/fuzzing

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[encode.go, line 305 [r1]](https://reviewable.io:443/reviews/cockroachdb/pq/5#-KCuzaKPFWCJXKKrWKfX:-KCuzaKPFWCJXKKrWKfY:-125422478) ([raw file](https://github.com/cockroachdb/pq/blob/d626cc110baa6dbbe41734fea8915f9c77df25d4/encode.go#L305)):_
this is a clever way of reducing the diff. nicely done. could you move this up to where `expect` and `mustAtoi` were previously, so that the diff is even smaller? anticipating upstream will want that.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/pq/5#-:-KCv-6-6nhDgQwlyXFmU:1417088721)_

**Comment by danhhz** [comment]
Thanks, I'll check the fuzzing stuff in on a branch somewhere.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[encode.go, line 305 [r1]](https://reviewable.io:443/reviews/cockroachdb/pq/5#-KCuzaKPFWCJXKKrWKfX:-KCv4Fz6zBujojo4Yvwy:676635175) ([raw file](https://github.com/cockroachdb/pq/blob/d626cc110baa6dbbe41734fea8915f9c77df25d4/encode.go#L305)):_
Done

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/pq/5#-:-KCv4TEYGKkeTVJPQ07r:-2084988652)_

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/pq/5)_

**Comment by danhhz** [comment]
Fuzzing branch is at https://github.com/paperstreet/pq/tree/fuzzing

**Comment by tbg** [comment]
We have a fork of `go-fuzz` in `cockroachdb`, might want to throw it in there (and update while you're at it).

**Comment by danhhz** [comment]
Done. Now in https://github.com/cockroachdb/go-fuzz/tree/master/examples/libpq instead!

**Pull request merged**
