### PR TITLE
Add rows.Tag() to enable access to the completion tag.

### PR DESCRIPTION
**Pull request by petermattis**
Enable access to the command completion tag for statements executed via
`conn.Query`.

TODO: Add a test. And is this the interface we want? It works nicely for https://github.com/cockroachdb/cockroach/issues/3993, but perhaps we should be parsing the completion tag and providing access to a `driver.Result`. The downside to that approach is that we'd have to reconstitute the tag if we want to mirror the `psql` output.

### CODE REVIEW

**Comment by bdarnell** [comment]
I don't think we need to mimic the `psql` output by printing the tag (e.g. mysql doesn't have anything analogous). I would prefer to expose `driver.Result` instead of the raw tag.

How is the caller supposed to know when `Tag()` (or its `driver.Result` analogue) has a meaningful value?

**Comment by petermattis** [comment]
See the latest commit in https://github.com/cockroachdb/cockroach/pull/4081. I always retrieve the tag from the rows. If the result had 0 columns I output the tag instead of any results. I could do something similar with `driver.Result`. Any thoughts on what the text should say? `%d row(s) affected`?

**Comment by petermattis** [comment]
The `mysql` tool reports output like:

```
mysql> insert into test.test values (1), (2);
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0
```

**Comment by bdarnell** [comment]
There is an edge case with checking for zero columns: It is possible (but maybe nonsensical?) for a SELECT to return no rows and no columns. We support tables with no columns, so `CREATE TABLE empty (); SELECT * FROM empty` will return an empty result set. In this implementation it would retain the result and tag from the last non-select command.

**Comment by petermattis** [comment]
@bdarnell Yeah, that isn't handled properly. This is what is currently output:

```
root@:15432> select * from test;
SELECT 3
```

Do you think this is worth detecting? I could detect when the operation was a `SELECT` and always output the rows, but that leads to this confusing output:

```
root@:15432> select * from test;
+
+
```

That rendering of that "pretty" table is wrong. It could be fixed in some manner, but I think outputting the tag and count of matching rows is preferable.

**Comment by petermattis** [comment]
And here is the behavior using the `-e` flag:

```
~ ./cockroach sql --insecure -e 'select * from test.test'
3 rows




```

**Comment by bdarnell** [comment]
I'd be fine with either `SELECT 0` or the weird (but logically consistent) `+\n+` thing for this edge case. I wouldn't match on `tag == "SELECT" but would prefer to see whether we have gotten an empty RowDescription or not (although that is tricky with the prepared-statement protocol). That would also cover zero-column`SHOW` statements (etc) if there are any. 

I had also missed that even selects send a command tag, so it wouldn't bleed through from the previous statement. But then where's the `3` coming from?

**Comment by petermattis** [comment]
We return `SELECT <num-rows>` as the tag when performing a select. Didn't you write that code?

I prefer `SELECT <num-rows>` over the oddly formatted table.

**Comment by bdarnell** [comment]
Yes, but why is the row count 3 instead of 0? Can you actually insert into a zero-column table? (I guess that should be possible now that I think about it, but both cockroach and postgres fail with a syntax error). If you can actually have zero columns with non-zero rows, then I'd prefer to output a blank line for each row (decorated however the "pretty" formatter wants to mangle it)

**Comment by petermattis** [comment]
Yes, you can insert into a zero-column table:

```
INSERT INTO test (rowid) VALUES (1), (2), (3)
```

The count was 3 because I did the above.

**Comment by bdarnell** [comment]
Ah, OK. (We should really disallow inserts into the hidden rowid column IMHO). I think that if the server gave us any DataRow messages then we should print the response in tabular form instead of tag form, although since #4548 the server also skips sending any rows back when there are no columns (and I don't think it's worth digging any deeper here)

LGTM

**Pull request merged**
